{% set version = "0.13.4" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 8ee5d1b69f64bc0e9379667455ee3585849d5e6bcd3f3e48e58ba6cadadfead5

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.32                        # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.32
    # Do not add any constraint on numpy here to use global pinning
    - numpy
    - scipy >=1.3
    - pandas >=1.0
    - patsy >=0.5.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3
    - pandas >=1.0
    - patsy >=0.5.2
    - packaging
test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: INSTALL.txt
  summary: Statistical computations and models for use with SciPy
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
    - bashtage
