{% set version = "0.14.4" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 5d69e0f39060dc72c067f9bb6e8033b6dccdb0bae101d76a7ef0bcc94e898b67

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.10,<4                     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.0.10,<4
    # Do not add any constraint on numpy here to use global pinning
    - numpy
    - scipy >=1.13.0,<1.16.0
    - pandas >=1.4
    - patsy >=0.5.6
    - setuptools_scm >=8.0.0,<9
  run:
    - numpy <3,>=1.22.3
    - python
    - scipy !=1.9.2,>=1.8,<1.16.0
    - pandas !=2.1.0,>=1.4
    - patsy >=0.5.6
    - packaging >=21.3
test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: INSTALL.txt
  summary: Statistical computations and models for use with SciPy
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
    - bashtage
