{% set version = "0.12.1" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: a271b4ccec190148dccda25f0cbdcbf871f408fc1394a10a7dc1af4a62b91c8e

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - scipy >=1.2
    - pandas >=0.23
    - patsy >=0.5.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2
    - pandas >=0.23
    - patsy >=0.5.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: INSTALL.txt
  summary: 'Statistical computations and models for use with SciPy'
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
