{% set version = "0.8.0" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 26431ab706fbae896db7870a0892743bfbb9f5c83231644692166a31d2d86048

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.11.*
    - scipy
    - pandas
    - patsy
  run:
    - python
    - numpy >=1.11
    - scipy
    - pandas
    - patsy

test:
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD 3-Clause
  summary: 'Statistical computations and models for use with SciPy'

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
