{% set version = "0.14.0" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 6875c7d689e966d948f15eb816ab5616f4928706b180cf470fd5907ab6f647a4

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.26,<3                    # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.26,<3
    # Do not add any constraint on numpy here to use global pinning
    - numpy
    - scipy >=1.4
    - pandas >=1.0
    - patsy >=0.5.2
    - setuptools_scm >=7.0.0,<7.1.dev0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy !=1.9.2,>=1.4
    - pandas >=1.0
    - patsy >=0.5.2
    - packaging >=21.3
test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: INSTALL.txt
  summary: Statistical computations and models for use with SciPy
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
    - bashtage
