appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: EjWDmEvwRBEe2bRiptUn9WIm356+zYLRIIvK+rjk2e4QZBlgxVc9CfOnOrTWkX9UId3xaAdWRru4k88RMbYURXfKwmGO/SiUMDWdfrAxn+QiVptjpgZJxwGD7uAfB127N4GCMfjw07m3T421GcX8avWPQ57o5LfwYrYkU/Rsau6eiFv+PUP9XQqw/I5pt3ncZonWzQb39S+pa8xKUNGmhFdeYf6Jhca6UoMIcz69Y3ZSoF1PPz+VK+2IStOPAhsbYTZ2se++K7tBewzfGDtYA8i3Uh9wo6uukSEKOWbuU/fKaZJdrBFRcQxyDEW87QsMDMsixH2Gbo2bnsDeIDPmmdmQ1GD0APUmqNCrXFsMU9mWGs7jh6tT+jbyIKXfo7/OrO0L2Dk7Y8AjsSZBkcQC0bYjmsr0K9lIg2afbORSDWi6k1SjwYu3zY+wATEXRxy3AmcMqqzf+fQMPxhpXluV1KU2fbjCNDKaG89MylUBNBR45XujBotHO37DBTppioUWn3dirtMPO0u1t3EXv/ajh4o7G4ep1VSr5biDJDKk3f4ol37xLWez8+aZ8YNIutO/tFZERSy6IFy1tCFzyaE0tdUf1wiYa3k/UkOauF1Vpr9/bpwWmhDVPEzJIPxKDlbB3LXeyf17vXRjPCTmkzEPnqp1pntE8PuWAm+vlBHC8MQ=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
